vsim mips

add wave reset
add wave clk
add wave PcAdderOut
add wave PcOut
add wave instructure1
add wave adder2adder1
add wave adderResult2
add wave andRes
add wave regWrite4
add wave instructure2
add wave adder2adder2
add wave signExtendOut1
add wave MuxMemout
add wave muxInsOut3
add wave readData11
add wave readData21
add wave regDst1
add wave branchne2
add wave branch1
add wave memRead1
add wave memtoReg1
add wave aluOp1
add wave memWrite1
add wave aluSrc1
add wave regWrite1
add wave readData12
add wave readData22
add wave shiftResult
add wave signExtendOut2
add wave adder2adder3
add wave adderResult1
add wave partOfInstructor
add wave muxInsOut1
add wave MuxRegsout
add wave operation
add wave ALUzero1
add wave ALUzerotmp
add wave ALUout1
add wave regDst2
add wave branchne2
add wave branch2
add wave memRead2
add wave memtoReg2
add wave aluOp2
add wave memWrite2
add wave aluSrc2
add wave regWrite2
add wave ALUzero2
add wave ALUout2
add wave readData23
add wave muxInsOut2
add wave MemoryDataRead1
add wave branch3
add wave memRead3
add wave memtoReg3
add wave memWrite3
add wave regWrite3
add wave MemoryDataRead2
add wave ALUout3
add wave memtoReg4

;run 200